### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by daniel-jodlos**

### CODE REVIEW

**Comment by mickel8** [comment]
PRs that only fixes typo should be disallowed :smile:

**Review by mat-hek — APPROVED** [review]
with heavy heart...

**Comment by mickel8** [comment]
Can't believe

**Comment by mat-hek** [comment]
@mickel8 no worries, it won't count towards his stats!
image

**Comment by daniel-jodlos** [comment]
> In memory of The Old Software Plumber
> Michał Śledź, circa 2022

(*) Sometimes one needs to bring up an old meme to make sure it's definitely dead.

**Pull request merged**
