### PR TITLE
Refactor closing issue message and add upgrading guide for v0.12

### PR DESCRIPTION
**Pull request by FelonEkonom**

### CODE REVIEW

**Review by mat-hek — APPROVED** [review]

**Comment by mat-hek** [comment]
@FelonEkonom shouldn't this be merged to the v0.12 branch?

**Review by mat-hek — COMMENTED** [review]
Shouldn't this be merged to the v0.12 branch?

**Review by mat-hek — CHANGES_REQUESTED** [review]
Shouldn't this be merged to the v0.12 branch?

**Comment by FelonEkonom** [comment]
Upgrading guide from this PR already exists on v0.12 branch. This PR puts it on master branch as well.

**Review by mat-hek — APPROVED** [review]

**Pull request merged**
